import {
  CompItem,
  DealTags,
  ForecastedRevenueInput,
  LeaderboardEntry,
  Market,
  OperatingExpense,
  OptimizationItem,
  Property,
  PurchaseDetailsInput,
  SubmissionRecord,
  TaxesInput,
  UnderwritingData,
} from "@/types";
import { calculateUnderwriting, scoreSubmission } from "./calculations";

export const INITIAL_MARKETS: Market[] = [
  {
    id: 1,
    slug: "smoky-blue-ridge-mountains",
    name: "Smoky & Blue Ridge Mountains",
    state: "TN / GA",
    region: "Southern Appalachia",
    timezone: "America/New_York",
    description:
      "Drive-to cabin market spanning the Tennessee Smokies and north Georgia mountains. Year-round demand; scenic mountain views and hot tubs drive ADR.",
    property_count: 3,
  },
  {
    id: 2,
    slug: "broken-bow",
    name: "Broken Bow",
    state: "OK",
    region: "Ouachita Mountains",
    timezone: "America/Chicago",
    description:
      "Hochatown / Broken Bow luxury cabin retreat fed by Dallas-Fort Worth and Oklahoma City metros. New-build heavy, light regulation, high weekend occupancy.",
    property_count: 1,
  },
  {
    id: 3,
    slug: "central-florida",
    name: "Central Florida",
    state: "FL",
    region: "Orlando Metro",
    timezone: "America/New_York",
    description:
      "Theme-park resort communities around Kissimmee and Davenport. Large themed vacation villas, HOA-managed amenities, cohost-friendly, steady international demand.",
    property_count: 1,
  },
  {
    id: 4,
    slug: "texas-gulf-coast",
    name: "Texas Gulf Coast",
    state: "TX",
    region: "Coastal Bend",
    timezone: "America/Chicago",
    description:
      "Port Aransas and Mustang Island premier beach community. Strong summer seasonality with top-decile peak ADR and premium private pool appeal.",
    property_count: 1,
  },
];

export const INITIAL_PROPERTIES: Property[] = [
  {
    zpid: "41234567",
    market_id: 1,
    market_name: "Smoky & Blue Ridge Mountains",
    address: "1240 Ski View Dr, Gatlinburg, TN 37738",
    address_street: "1240 Ski View Dr",
    address_city: "Gatlinburg",
    address_state: "TN",
    address_zipcode: "37738",
    price: "$675,000",
    unformatted_price: 675000,
    beds: 3,
    baths: 3.0,
    area: 2150,
    latitude: 35.7143,
    longitude: -83.5102,
    home_type: "SINGLE_FAMILY",
    home_status: "FOR_SALE",
    time_on_zillow: "12 days",
    img_src: "https://picsum.photos/seed/gatlinburg/640/420",
    detail_url: "https://www.zillow.com/homedetails/1240-Ski-View-Dr/41234567_zpid/",
    status: "in_progress",
    attempts: 1,
    latest_accuracy: 100,
    latest_rating: "best",
    best_accuracy: 100,
    best_rating: "best",
    active_underwriting_id: "draft-41234567",
    latest_submission_id: "sub-seed-1",
  },
  {
    zpid: "52345678",
    market_id: 2,
    market_name: "Broken Bow",
    address: "88 Lakeshore Ln, Broken Bow, OK 74728",
    address_street: "88 Lakeshore Ln",
    address_city: "Broken Bow",
    address_state: "OK",
    address_zipcode: "74728",
    price: "$540,000",
    unformatted_price: 540000,
    beds: 2,
    baths: 2.0,
    area: 1600,
    latitude: 34.1324,
    longitude: -94.7405,
    home_type: "SINGLE_FAMILY",
    home_status: "FOR_SALE",
    time_on_zillow: "5 days",
    img_src: "https://picsum.photos/seed/brokenbow/640/420",
    detail_url: "https://www.zillow.com/homedetails/88-Lakeshore-Ln/52345678_zpid/",
    status: "not_started",
    attempts: 0,
    latest_accuracy: null,
    latest_rating: null,
    best_accuracy: null,
    best_rating: null,
    active_underwriting_id: null,
    latest_submission_id: null,
  },
  {
    zpid: "63456789",
    market_id: 3,
    market_name: "Central Florida",
    address: "3402 Palm Isle Ct, Kissimmee, FL 34747",
    address_street: "3402 Palm Isle Ct",
    address_city: "Kissimmee",
    address_state: "FL",
    address_zipcode: "34747",
    price: "$895,000",
    unformatted_price: 895000,
    beds: 6,
    baths: 5.5,
    area: 3400,
    latitude: 28.32,
    longitude: -81.61,
    home_type: "SINGLE_FAMILY",
    home_status: "FOR_SALE",
    time_on_zillow: "27 days",
    img_src: "https://picsum.photos/seed/kissimmee/640/420",
    detail_url: "https://www.zillow.com/homedetails/3402-Palm-Isle-Ct/63456789_zpid/",
    status: "not_started",
    attempts: 0,
    latest_accuracy: null,
    latest_rating: null,
    best_accuracy: null,
    best_rating: null,
    active_underwriting_id: null,
    latest_submission_id: null,
  },
  {
    zpid: "74567890",
    market_id: 1,
    market_name: "Smoky & Blue Ridge Mountains",
    address: "215 Aspen Ridge Rd, Blue Ridge, GA 30513",
    address_street: "215 Aspen Ridge Rd",
    address_city: "Blue Ridge",
    address_state: "GA",
    address_zipcode: "30513",
    price: "$725,000",
    unformatted_price: 725000,
    beds: 4,
    baths: 3.5,
    area: 2600,
    latitude: 34.864,
    longitude: -84.324,
    home_type: "SINGLE_FAMILY",
    home_status: "FOR_SALE",
    time_on_zillow: "41 days",
    img_src: "https://picsum.photos/seed/blueridge/640/420",
    detail_url: "https://www.zillow.com/homedetails/215-Aspen-Ridge-Rd/74567890_zpid/",
    status: "not_started",
    attempts: 0,
    latest_accuracy: null,
    latest_rating: null,
    best_accuracy: null,
    best_rating: null,
    active_underwriting_id: null,
    latest_submission_id: null,
  },
  {
    zpid: "85678901",
    market_id: 4,
    market_name: "Texas Gulf Coast",
    address: "9 Dune Walk, Port Aransas, TX 78373",
    address_street: "9 Dune Walk",
    address_city: "Port Aransas",
    address_state: "TX",
    address_zipcode: "78373",
    price: "$1,150,000",
    unformatted_price: 1150000,
    beds: 5,
    baths: 4.0,
    area: 2900,
    latitude: 27.8339,
    longitude: -97.0611,
    home_type: "SINGLE_FAMILY",
    home_status: "FOR_SALE",
    time_on_zillow: "9 days",
    img_src: "https://picsum.photos/seed/portaransas/640/420",
    detail_url: "https://www.zillow.com/homedetails/9-Dune-Walk/85678901_zpid/",
    status: "not_started",
    attempts: 0,
    latest_accuracy: null,
    latest_rating: null,
    best_accuracy: null,
    best_rating: null,
    active_underwriting_id: null,
    latest_submission_id: null,
  },
  {
    zpid: "96789012",
    market_id: 1,
    market_name: "Smoky & Blue Ridge Mountains",
    address: "47 Cedar Hollow Rd, Sevierville, TN 37876",
    address_street: "47 Cedar Hollow Rd",
    address_city: "Sevierville",
    address_state: "TN",
    address_zipcode: "37876",
    price: "$449,000",
    unformatted_price: 449000,
    beds: 2,
    baths: 2.0,
    area: 1350,
    latitude: 35.8681,
    longitude: -83.5619,
    home_type: "SINGLE_FAMILY",
    home_status: "FOR_SALE",
    time_on_zillow: "3 days",
    img_src: "https://picsum.photos/seed/sevierville/640/420",
    detail_url: "https://www.zillow.com/homedetails/47-Cedar-Hollow-Rd/96789012_zpid/",
    status: "not_started",
    attempts: 0,
    latest_accuracy: null,
    latest_rating: null,
    best_accuracy: null,
    best_rating: null,
    active_underwriting_id: null,
    latest_submission_id: null,
  },
];

export const REFERENCE_UNDERWRITINGS: Record<string, UnderwritingData> = {
  "41234567": {
    id: "ref-41234567",
    zpid: "41234567",
    updated_at: new Date().toISOString(),
    bedrooms: 3,
    bathrooms: 3.0,
    sleep_count_low: 8,
    sleep_count_high: 10,
    purchase_details: {
      purchase_price: 660000,
      down_payment_pct: 0.2,
      interest_rate: 0.0699,
      mortgage_years: 30,
      closing_costs_pct: 0.03,
    },
    forecasted_revenue: {
      co_hosting_fee_pct: 0,
      annual_re_appreciation_pct: 0.03,
      low_revenue: 105000,
      mid_revenue: 125000,
      high_revenue: 142000,
    },
    taxes: {
      land_assumptions_pct: 0.2,
      sla_multiplier_pct: 0.25,
      bonus_amount_pct: 0.6,
      tax_rate_pct: 0.37,
    },
    optimization_items: [
      { id: "opt-1", category: "Furniture & design", total_price: 45000 },
      { id: "opt-2", category: "Hot tub", total_price: 12000 },
      { id: "opt-3", category: "Game room", total_price: 9000 },
    ],
    operating_expenses: [
      { id: "opex-1", expense_name: "Utilities", monthly_amount: 450 },
      { id: "opex-2", expense_name: "Internet", monthly_amount: 90 },
      { id: "opex-3", expense_name: "Insurance", monthly_amount: 320 },
      { id: "opex-4", expense_name: "Property Taxes", monthly_amount: 410 },
      { id: "opex-5", expense_name: "Lawn and Snow", monthly_amount: 120 },
      { id: "opex-6", expense_name: "Supplies", monthly_amount: 150 },
      { id: "opex-7", expense_name: "Software", monthly_amount: 60 },
      { id: "opex-8", expense_name: "Maintenance Reserve", monthly_amount: 250 },
    ],
    comp_set: [
      { id: "comp-1", listing_url: "https://www.airbnb.com/rooms/1001", revenue: 118000, bedrooms: 3, sleeps: 9, is_favourite: true },
      { id: "comp-2", listing_url: "https://www.airbnb.com/rooms/1002", revenue: 131000, bedrooms: 3, sleeps: 10 },
      { id: "comp-3", listing_url: "https://www.airbnb.com/rooms/1003", revenue: 109500, bedrooms: 3, sleeps: 8 },
    ],
    tags: {
      turnkey: false,
      furnished: false,
      luxury: false,
      tax_efficient: true,
      new_construction: false,
      existing_airbnb: true,
      arv: false,
      high_cash_on_cash: true,
      low_cash_on_cash: false,
      add_inground_pool: false,
      waterfront: false,
      remote: false,
      can_support_cohost: true,
      renovation_level: 2,
      deal_complexity: 2,
    },
    deal_pitch: "Mountain-view cabin near Ober; strong year-round demand.",
    analyst_notes: "Gatlinburg has strong summer and fall foliage peaks. High occupancy on 3-beds with game rooms.",
  },
  "52345678": {
    id: "ref-52345678",
    zpid: "52345678",
    updated_at: new Date().toISOString(),
    bedrooms: 2,
    bathrooms: 2.0,
    sleep_count_low: 6,
    sleep_count_high: 8,
    purchase_details: {
      purchase_price: 525000,
      down_payment_pct: 0.25,
      interest_rate: 0.0699,
      mortgage_years: 30,
      closing_costs_pct: 0.03,
    },
    forecasted_revenue: {
      co_hosting_fee_pct: 0,
      annual_re_appreciation_pct: 0.03,
      low_revenue: 82000,
      mid_revenue: 96000,
      high_revenue: 108000,
    },
    taxes: {
      land_assumptions_pct: 0.2,
      sla_multiplier_pct: 0.25,
      bonus_amount_pct: 0.6,
      tax_rate_pct: 0.37,
    },
    optimization_items: [
      { id: "opt-1", category: "Furniture & design", total_price: 38000 },
      { id: "opt-2", category: "Hot tub", total_price: 11000 },
    ],
    operating_expenses: [
      { id: "opex-1", expense_name: "Utilities", monthly_amount: 380 },
      { id: "opex-2", expense_name: "Internet", monthly_amount: 85 },
      { id: "opex-3", expense_name: "Insurance", monthly_amount: 260 },
      { id: "opex-4", expense_name: "Property Taxes", monthly_amount: 330 },
      { id: "opex-5", expense_name: "Lawn", monthly_amount: 100 },
      { id: "opex-6", expense_name: "Supplies", monthly_amount: 120 },
      { id: "opex-7", expense_name: "Software", monthly_amount: 60 },
      { id: "opex-8", expense_name: "Maintenance Reserve", monthly_amount: 200 },
    ],
    comp_set: [
      { id: "comp-1", listing_url: "https://www.airbnb.com/rooms/2001", revenue: 94000, bedrooms: 2, sleeps: 6 },
      { id: "comp-2", listing_url: "https://www.airbnb.com/rooms/2002", revenue: 101000, bedrooms: 2, sleeps: 8 },
    ],
    tags: {
      turnkey: true,
      furnished: true,
      luxury: false,
      tax_efficient: true,
      new_construction: true,
      existing_airbnb: false,
      arv: false,
      high_cash_on_cash: true,
      low_cash_on_cash: false,
      add_inground_pool: false,
      waterfront: false,
      remote: false,
      can_support_cohost: false,
      renovation_level: 1,
      deal_complexity: 1,
    },
    deal_pitch: "New-build luxury cabin in Hochatown; turnkey.",
  },
  "63456789": {
    id: "ref-63456789",
    zpid: "63456789",
    updated_at: new Date().toISOString(),
    bedrooms: 6,
    bathrooms: 5.5,
    sleep_count_low: 14,
    sleep_count_high: 16,
    purchase_details: {
      purchase_price: 870000,
      down_payment_pct: 0.2,
      interest_rate: 0.0699,
      mortgage_years: 30,
      closing_costs_pct: 0.03,
    },
    forecasted_revenue: {
      co_hosting_fee_pct: 0.1,
      annual_re_appreciation_pct: 0.03,
      low_revenue: 140000,
      mid_revenue: 165000,
      high_revenue: 185000,
    },
    taxes: {
      land_assumptions_pct: 0.2,
      sla_multiplier_pct: 0.25,
      bonus_amount_pct: 0.6,
      tax_rate_pct: 0.37,
    },
    optimization_items: [
      { id: "opt-1", category: "Furniture & design", total_price: 70000 },
      { id: "opt-2", category: "Themed bedrooms", total_price: 25000 },
      { id: "opt-3", category: "Pool heater & screen", total_price: 9000 },
      { id: "opt-4", category: "Game room", total_price: 15000 },
    ],
    operating_expenses: [
      { id: "opex-1", expense_name: "Utilities", monthly_amount: 700 },
      { id: "opex-2", expense_name: "Internet", monthly_amount: 100 },
      { id: "opex-3", expense_name: "Insurance", monthly_amount: 520 },
      { id: "opex-4", expense_name: "Property Taxes", monthly_amount: 900 },
      { id: "opex-5", expense_name: "HOA", monthly_amount: 380 },
      { id: "opex-6", expense_name: "Pool Service", monthly_amount: 180 },
      { id: "opex-7", expense_name: "Lawn", monthly_amount: 140 },
      { id: "opex-8", expense_name: "Supplies", monthly_amount: 220 },
      { id: "opex-9", expense_name: "Software", monthly_amount: 60 },
      { id: "opex-10", expense_name: "Maintenance Reserve", monthly_amount: 350 },
    ],
    comp_set: [
      { id: "comp-1", listing_url: "https://www.airbnb.com/rooms/3001", revenue: 158000, bedrooms: 6, sleeps: 14 },
      { id: "comp-2", listing_url: "https://www.airbnb.com/rooms/3002", revenue: 172000, bedrooms: 6, sleeps: 16 },
    ],
    tags: {
      turnkey: false,
      furnished: false,
      luxury: true,
      tax_efficient: true,
      new_construction: false,
      existing_airbnb: true,
      arv: false,
      high_cash_on_cash: true,
      low_cash_on_cash: false,
      add_inground_pool: false,
      waterfront: false,
      remote: false,
      can_support_cohost: true,
      renovation_level: 3,
      deal_complexity: 3,
    },
    deal_pitch: "Large themed home near Disney; pool already in.",
  },
  "74567890": {
    id: "ref-74567890",
    zpid: "74567890",
    updated_at: new Date().toISOString(),
    bedrooms: 4,
    bathrooms: 3.5,
    sleep_count_low: 10,
    sleep_count_high: 12,
    purchase_details: {
      purchase_price: 690000,
      down_payment_pct: 0.2,
      interest_rate: 0.0699,
      mortgage_years: 30,
      closing_costs_pct: 0.03,
    },
    forecasted_revenue: {
      co_hosting_fee_pct: 0,
      annual_re_appreciation_pct: 0.03,
      low_revenue: 110000,
      mid_revenue: 128000,
      high_revenue: 145000,
    },
    taxes: {
      land_assumptions_pct: 0.2,
      sla_multiplier_pct: 0.25,
      bonus_amount_pct: 0.6,
      tax_rate_pct: 0.37,
    },
    optimization_items: [
      { id: "opt-1", category: "Furniture & design", total_price: 52000 },
      { id: "opt-2", category: "Hot tub", total_price: 12000 },
      { id: "opt-3", category: "Fire pit & deck", total_price: 8000 },
    ],
    operating_expenses: [
      { id: "opex-1", expense_name: "Utilities", monthly_amount: 480 },
      { id: "opex-2", expense_name: "Internet", monthly_amount: 90 },
      { id: "opex-3", expense_name: "Insurance", monthly_amount: 340 },
      { id: "opex-4", expense_name: "Property Taxes", monthly_amount: 450 },
      { id: "opex-5", expense_name: "Lawn", monthly_amount: 120 },
      { id: "opex-6", expense_name: "Supplies", monthly_amount: 160 },
      { id: "opex-7", expense_name: "Software", monthly_amount: 60 },
      { id: "opex-8", expense_name: "Maintenance Reserve", monthly_amount: 260 },
    ],
    comp_set: [],
    tags: {
      turnkey: false,
      furnished: false,
      luxury: false,
      tax_efficient: true,
      new_construction: false,
      existing_airbnb: false,
      arv: false,
      high_cash_on_cash: false,
      low_cash_on_cash: false,
      add_inground_pool: false,
      waterfront: false,
      remote: true,
      can_support_cohost: false,
      renovation_level: 2,
      deal_complexity: 2,
    },
    deal_pitch: "Long-range mountain views, 41 DOM gives negotiation room.",
  },
  "85678901": {
    id: "ref-85678901",
    zpid: "85678901",
    updated_at: new Date().toISOString(),
    bedrooms: 5,
    bathrooms: 4.0,
    sleep_count_low: 12,
    sleep_count_high: 14,
    purchase_details: {
      purchase_price: 1125000,
      down_payment_pct: 0.25,
      interest_rate: 0.0699,
      mortgage_years: 30,
      closing_costs_pct: 0.03,
    },
    forecasted_revenue: {
      co_hosting_fee_pct: 0,
      annual_re_appreciation_pct: 0.03,
      low_revenue: 165000,
      mid_revenue: 192000,
      high_revenue: 215000,
    },
    taxes: {
      land_assumptions_pct: 0.2,
      sla_multiplier_pct: 0.25,
      bonus_amount_pct: 0.6,
      tax_rate_pct: 0.37,
    },
    optimization_items: [
      { id: "opt-1", category: "Furniture & design", total_price: 65000 },
      { id: "opt-2", category: "Private pool", total_price: 75000 },
      { id: "opt-3", category: "Golf cart", total_price: 9000 },
    ],
    operating_expenses: [
      { id: "opex-1", expense_name: "Utilities", monthly_amount: 650 },
      { id: "opex-2", expense_name: "Internet", monthly_amount: 100 },
      { id: "opex-3", expense_name: "Insurance", monthly_amount: 1100 },
      { id: "opex-4", expense_name: "Property Taxes", monthly_amount: 1500 },
      { id: "opex-5", expense_name: "HOA", monthly_amount: 250 },
      { id: "opex-6", expense_name: "Pool Service", monthly_amount: 170 },
      { id: "opex-7", expense_name: "Lawn", monthly_amount: 120 },
      { id: "opex-8", expense_name: "Supplies", monthly_amount: 220 },
      { id: "opex-9", expense_name: "Software", monthly_amount: 60 },
      { id: "opex-10", expense_name: "Maintenance Reserve", monthly_amount: 400 },
    ],
    comp_set: [],
    tags: {
      turnkey: false,
      furnished: false,
      luxury: true,
      tax_efficient: true,
      new_construction: false,
      existing_airbnb: true,
      arv: false,
      high_cash_on_cash: true,
      low_cash_on_cash: false,
      add_inground_pool: true,
      waterfront: true,
      remote: false,
      can_support_cohost: false,
      renovation_level: 3,
      deal_complexity: 4,
    },
    deal_pitch: "Beach walk-over; pool add unlocks top-decile revenue.",
  },
  "96789012": {
    id: "ref-96789012",
    zpid: "96789012",
    updated_at: new Date().toISOString(),
    bedrooms: 2,
    bathrooms: 2.0,
    sleep_count_low: 4,
    sleep_count_high: 6,
    purchase_details: {
      purchase_price: 435000,
      down_payment_pct: 0.2,
      interest_rate: 0.0699,
      mortgage_years: 30,
      closing_costs_pct: 0.03,
    },
    forecasted_revenue: {
      co_hosting_fee_pct: 0,
      annual_re_appreciation_pct: 0.03,
      low_revenue: 68000,
      mid_revenue: 80000,
      high_revenue: 92000,
    },
    taxes: {
      land_assumptions_pct: 0.2,
      sla_multiplier_pct: 0.25,
      bonus_amount_pct: 0.6,
      tax_rate_pct: 0.37,
    },
    optimization_items: [
      { id: "opt-1", category: "Furniture & refresh", total_price: 28000 },
      { id: "opt-2", category: "Hot tub", total_price: 10000 },
    ],
    operating_expenses: [
      { id: "opex-1", expense_name: "Utilities", monthly_amount: 320 },
      { id: "opex-2", expense_name: "Internet", monthly_amount: 80 },
      { id: "opex-3", expense_name: "Insurance", monthly_amount: 220 },
      { id: "opex-4", expense_name: "Property Taxes", monthly_amount: 280 },
      { id: "opex-5", expense_name: "Lawn", monthly_amount: 90 },
      { id: "opex-6", expense_name: "Supplies", monthly_amount: 110 },
      { id: "opex-7", expense_name: "Software", monthly_amount: 60 },
      { id: "opex-8", expense_name: "Maintenance Reserve", monthly_amount: 180 },
    ],
    comp_set: [],
    tags: {
      turnkey: true,
      furnished: true,
      luxury: false,
      tax_efficient: true,
      new_construction: false,
      existing_airbnb: true,
      arv: false,
      high_cash_on_cash: true,
      low_cash_on_cash: false,
      add_inground_pool: false,
      waterfront: false,
      remote: false,
      can_support_cohost: false,
      renovation_level: 1,
      deal_complexity: 1,
    },
    deal_pitch: "Entry-level cabin in peaceful Sevierville valley; cash-flow steady.",
  },
};

// Prefilled trainee starter template for a property
export function createDraftUnderwriting(property: Property): UnderwritingData {
  const defaultTaxes: TaxesInput = {
    land_assumptions_pct: 0.2,
    sla_multiplier_pct: 0.25,
    bonus_amount_pct: 0.6,
    tax_rate_pct: 0.37,
  };

  const defaultPurchase: PurchaseDetailsInput = {
    purchase_price: property.unformatted_price,
    down_payment_pct: 0.2,
    interest_rate: 0.0699,
    mortgage_years: 30,
    closing_costs_pct: 0.03,
  };

  const defaultRevenue: ForecastedRevenueInput = {
    co_hosting_fee_pct: 0.0,
    annual_re_appreciation_pct: 0.03,
    low_revenue: 0,
    mid_revenue: 0,
    high_revenue: 0,
  };

  const defaultOptimization: OptimizationItem[] = [
    { id: "opt-1", category: "Furniture & design", total_price: 35000 },
    { id: "opt-2", category: "Hot tub", total_price: 11000 },
  ];

  const defaultOperating: OperatingExpense[] = [
    { id: "opex-1", expense_name: "Utilities", monthly_amount: 400 },
    { id: "opex-2", expense_name: "Internet & WiFi", monthly_amount: 85 },
    { id: "opex-3", expense_name: "Insurance (STR)", monthly_amount: 300 },
    { id: "opex-4", expense_name: "Property Taxes", monthly_amount: 380 },
    { id: "opex-5", expense_name: "Lawn & Snow Care", monthly_amount: 110 },
    { id: "opex-6", expense_name: "Guest Supplies & Consumables", monthly_amount: 140 },
    { id: "opex-7", expense_name: "Software & Smart Locks", monthly_amount: 60 },
    { id: "opex-8", expense_name: "Maintenance Reserve", monthly_amount: 220 },
  ];

  const defaultTags: DealTags = {
    turnkey: false,
    furnished: false,
    luxury: false,
    tax_efficient: true,
    new_construction: false,
    existing_airbnb: false,
    arv: false,
    high_cash_on_cash: false,
    low_cash_on_cash: false,
    add_inground_pool: false,
    waterfront: false,
    remote: false,
    can_support_cohost: false,
    renovation_level: 2,
    deal_complexity: 2,
  };

  const draft: UnderwritingData = {
    id: `draft-${property.zpid}`,
    zpid: property.zpid,
    updated_at: new Date().toISOString(),
    bedrooms: property.beds,
    bathrooms: property.baths,
    sleep_count_low: property.beds * 2,
    sleep_count_high: property.beds * 2 + 2,
    purchase_details: defaultPurchase,
    forecasted_revenue: defaultRevenue,
    taxes: defaultTaxes,
    optimization_items: defaultOptimization,
    operating_expenses: defaultOperating,
    comp_set: [],
    tags: defaultTags,
    deal_pitch: "",
  };

  draft.calculations = calculateUnderwriting(
    draft.purchase_details,
    draft.forecasted_revenue,
    draft.taxes,
    draft.optimization_items,
    draft.operating_expenses
  );

  return draft;
}

export const INITIAL_LEADERBOARD: LeaderboardEntry[] = [
  {
    rank: 1,
    id: "usr-1",
    name: "Sarah Chen",
    role: "Senior STR Underwriter",
    avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=120&auto=format&fit=crop&q=80",
    completed_deals: 6,
    best_score: 100,
    average_accuracy: 98.4,
    best_rating_count: 6,
    streak: 8,
  },
  {
    rank: 2,
    id: "usr-2",
    name: "Alex Rivera",
    role: "Acquisitions Associate",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=120&auto=format&fit=crop&q=80",
    completed_deals: 5,
    best_score: 100,
    average_accuracy: 94.0,
    best_rating_count: 4,
    streak: 4,
  },
  {
    rank: 3,
    id: "usr-current",
    name: "You (Analyst Trainee)",
    role: "Underwriting Fellow",
    avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=120&auto=format&fit=crop&q=80",
    completed_deals: 1,
    best_score: 100,
    average_accuracy: 100.0,
    best_rating_count: 1,
    streak: 1,
    is_current_user: true,
  },
  {
    rank: 4,
    id: "usr-4",
    name: "Marcus Vance",
    role: "Analyst Trainee",
    avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=120&auto=format&fit=crop&q=80",
    completed_deals: 4,
    best_score: 70,
    average_accuracy: 72.5,
    best_rating_count: 1,
    streak: 2,
  },
  {
    rank: 5,
    id: "usr-5",
    name: "Elena Rostova",
    role: "Analyst Trainee",
    avatar: "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=120&auto=format&fit=crop&q=80",
    completed_deals: 3,
    best_score: 70,
    average_accuracy: 65.0,
    best_rating_count: 0,
    streak: 0,
  },
];
